{'architecture':{'choose_model':'GATNet',
                'learning_rate':0.0005,
                'batch_size':4096,
                'n_epochs':14},
'data': {'path_to_train':'./data/graphs_NewDataset_train.pt',
        'path_to_test':'./data/graphs_NewDataset_test.pt',
        'size_train':0.8,
        'path_to_save':'./data/out_train/', 
        'model_name':'GATNet_test_tenmillion'}}