data:
  path_to_train: 'data/graphs_NewDataset_train_new.pt'
  path_to_test: 'data/graphs_NewDataset_test_new.pt'
  size_train: 0.80
  path_to_save: "/home/jmsardain/JetCalib/PUMitigation/final/ckpts/GATNet/"
  model_name: "GATNet_"

architecture:
  batch_size: 2048
  n_epochs: 100
  learning_rate: 0.001
  choose_model: "GATNet" ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
