data:
  path_to_test: 'data/graphs_NewDataset_test.pt'
  path_classifier: '/home/jmsardain/JetCalib/PUMitigation/final/ckpts/GATNet/GATNet_e097_losstrain22.323_lossval104.455.pt'
  path_to_save: "/home/jmsardain/JetCalib/PUMitigation/final/ckpts/GATNet/"
  model_name: "GATNet_"

architecture:
  batch_size: 1000
  n_epochs: 11
  choose_model: "GATNet" ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
